{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "palaceoftruth.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "palaceoftruth.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ include "palaceoftruth.fullname" . }}-backend
  endpoints:
    - port: http
      path: {{ .Values.metrics.path | quote }}
      honorLabels: {{ .Values.metrics.serviceMonitor.honorLabels }}
      interval: {{ .Values.metrics.serviceMonitor.interval | quote }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout | quote }}
{{- end }}
