{{- if eq (include "palaceoftruth.valkeySentinelEnabled" .) "true" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "palaceoftruth.valkeySentinelName" . }}-config
  labels:
    {{- include "palaceoftruth.labels" . | nindent 4 }}
data:
  sentinel.conf: |
    {{- include "palaceoftruth.valkeySentinelConfig" . | nindent 4 }}
{{- end }}
